language:
  java

addons:
  sonarcloud:
    organization: "actividad-pipeline"
    token:
      secure: "50ade4a6184d04f33f2f0ccfa0cc2f8cfe1aaa13"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  - ant dist
