language:
  java

addons:
  sonarcloud:
    organization: "actividad-pipeline"
    token:
      secure: "YFuX0bwx66VF+t5UjvC3drZzlCVfopumazb5OEvOmQXDFxEfPUkBVHi22+w1SJxKZN8lvqHHJqKlkZI6BYp6jEERJo/4mhLB1qDKoVCrf6MZaQFtXgjX9P3k8rxuJeFJygRjqQUYQif1TWfpZQczpfIvkE/B2AxhCGFmfUR0DBL3HkkJadTCtH6ChLp1z3cVfgjIVbjhy7wyETIRdlcMX2AIsGGkzo0MmzCzdUDWo0lhMtNyU+Jtj1LNan7pyzcE0GW37GnvpFcxzp/QHJAEr2BU4p9wcQdVSnm8b+6v7hnsTAL6iOitHWDFH51na1h2M1OEmwr8qgHw/gueKlUPQib7FI4grfV2SyzyC6wtdbDUUyWthPQlVw+X2ulc0jskv+kq1DfPZOgvefWnm0aMUylcYmMmOBadcCsBklmJlaUnb/2oMwgmiZhZWH3kq02Nd2NUj/XNGnMfiH6hLNgAwuEaIjf9s+O+uOVpbcHGMcc2u0jUsBVQgKEQXpHzBcZbqHeQ1XF0GrE3ACQxv4AWJv+a3DxH2KshxDsBlXc/agdczBlbIU2y6jpfDYVGUUmpcH53vWCrOditg/xTZBGDVA11rn3eVd5sBVsqgnVwPUop7ym/QW9L4c07V6zx3veA3Psh7nv/XEUfdXnfDj4cJZQTIYBs7Ipo+YMlN3NaIGY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ant dist
  - sonar-scanner

